'use strict';
const $ = (s, root=document) => root.querySelector(s);
const icons={overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',content:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h5"/>',media:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m21 15-5-5L5 21"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18M8 15h2M14 15h2"/>',activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',settings:'<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/><path d="m9 3-1 3-3 1-2 3 2 2-1 3 3 2 2 4h4l2-3 3-1 3-3-2-3 1-3-3-2-1-3Z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/>',download:'<path d="M12 3v13m-5-5 5 5 5-5M4 16v5h16v-5"/>',check:'<path d="m5 12 4 4L19 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',edit:'<path d="m16 3 5 5-12 12-6 1 1-6ZM13 6l5 5"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',bulb:'<path d="M9 18h6M10 22h4M8 14a6 6 0 1 1 8 0l-1 4H9Z"/>',copy:'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.content}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='studio-cms-v1';
let state={version:1,revision:0,settings:{name:'Workspace owner',workspace:'Studio workspace'},entries:[],media:[],activity:[]};
let page='overview',filter='All content',query='',toastTimer,csrf='',signedIn=false,busy=false,setupRequired=false;
async function api(path, options={}) {
  let response;
  try { response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Studio-Request':'1','X-Studio-Origin':location.origin,'X-CSRF-Token':csrf,...options.headers},credentials:'same-origin'}); }
  catch { throw new Error('Cannot reach the server. Your changes have not been saved. Check the connection and try again.'); }
  let data;try{data=await response.json();}catch{throw new Error('This address is not serving the Studio API. Start the Node server with npm start and open its address.');}
  if(!response.ok){const error=new Error(data.error||'The request failed.');error.status=response.status;throw error;}
  return data;
}
function setBusy(value){busy=value;document.body.classList.toggle('saving',value);}
async function commit(action) {
  if(busy){toast('Please wait for the current save.');return false;}
  const previous=state;
  state=structuredClone(previous);
  let candidate;
  try{action();candidate=state;}finally{state=previous;}
  setBusy(true);
  try { state=await api('/api/workspace',{method:'PUT',body:JSON.stringify(candidate)});$('#editor-error').hidden=true;return true; }
  catch(error){toast(error.message);if($('#editor-dialog').open){$('#editor-error').hidden=false;$('#editor-error-text').textContent=error.message;}if(error.status===401)showAuth(false);return false;}
  finally{setBusy(false);}
}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4000)}
const dateLabel=d=>new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'short'});
const relative=d=>{const m=Math.max(0,Math.floor((Date.now()-new Date(d))/60000));return m<1?'Just now':m<60?`${m} min ago`:m<1440?`${Math.floor(m/60)} hr ago`:`${Math.floor(m/1440)} days ago`};
const badge=s=>`<span class="badge ${s.toLowerCase().replace(' ','-')}">${esc(s)}</span>`;
const action=(name,label,cls='secondary',id='')=>`<button class="button ${cls}" ${id?`id="${id}"`:''}>${icon(name)}${label}</button>`;
const heading=(title,subtitle,actions='')=>`<div class="page-heading"><div><span class="eyebrow">YOUR CREATIVE COMMAND CENTER</span><h1>${title}</h1><p>${subtitle}</p></div><div class="heading-actions">${actions}</div></div>`;
function shell(){const nav=[['overview','Overview'],['content','Content'],['media','Media library'],['calendar','Publishing calendar'],['activity','Activity'],['settings','Settings']];$('#nav').innerHTML=nav.map(([id,label],i)=>`${i===4?'<div class="nav-separator"></div>':''}<button class="nav-item ${page===id?'active':''}" data-nav="${id}">${icon(id)}${label}${id==='content'?`<span class="nav-count">${state.entries.length}</span>`:''}</button>`).join('');$('#crumb').textContent=nav.find(n=>n[0]===page)?.[1]||'Overview';const bytes=new Blob([JSON.stringify(state)]).size;$('#storage-value').textContent=`${(bytes/1024).toFixed(1)} KB`;$('#storage-bar').style.width=`${Math.min(100,bytes/20000000*100)}%`;$('.workspace strong').textContent=state.settings.workspace;$('.profile strong').textContent=state.settings.name;const initials=state.settings.name.split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase();document.querySelectorAll('.avatar').forEach(e=>e.textContent=initials);$('#search-button').innerHTML=icon('search')}
function contentPanel(full=false){return `<section class="panel"><div class="panel-head"><div><h2>${full?'All content':'Recent content'}</h2><p>${full?'Every idea, draft, and published story in one place.':'A little progress, every day.'}</p></div>${!full?'<button class="text-link" data-nav="content">View all content ↗</button>':''}</div><div class="filters"><div class="tabs">${['All content','Published','Draft','In review'].map(t=>`<button class="tab ${filter===t?'active':''}" data-filter="${t}">${t}</button>`).join('')}</div><div class="search-wrap">${icon('search')}<input aria-label="Search content" id="content-search" placeholder="Search content…" value="${esc(query)}"></div></div><div id="content-results">${rows(full)}</div></section>`}
function rows(full){const entries=state.entries.filter(e=>(filter==='All content'||e.status===filter)&&`${e.title} ${e.category} ${e.body}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>new Date(b.updated)-new Date(a.updated));const visible=full?entries:entries.slice(0,6);return `<div class="table-scroll"><table><thead><tr><th>Content name</th><th>Status</th><th class="optional-col">Last updated</th><th>Actions</th></tr></thead><tbody>${visible.map(e=>`<tr><td><div class="title-cell"><span class="cover ${e.category.toLowerCase()}">${icon(e.type==='Page'?'overview':'content')}</span><div><button class="entry-name" data-edit="${e.id}">${esc(e.title)}</button><div class="entry-sub">${esc(e.type)} <span>·</span> ${esc(e.category)}</div></div></div></td><td>${badge(e.status)}</td><td class="optional-col">${dateLabel(e.updated)}</td><td><div class="menu-actions"><button class="icon-button" title="Preview" aria-label="Preview ${esc(e.title)}" data-preview="${e.id}">${icon('eye')}</button><button class="icon-button" title="Duplicate" aria-label="Duplicate ${esc(e.title)}" data-copy="${e.id}">${icon('copy')}</button><button class="icon-button danger" title="Delete" aria-label="Delete ${esc(e.title)}" data-delete="${e.id}">${icon('trash')}</button></div></td></tr>`).join('')}</tbody></table>${!visible.length?'<div class="empty"><h3>No content found</h3><p>Try a different search or create your first story.</p></div>':''}</div><div class="table-bottom"><span>Showing ${visible.length} of ${entries.length} entries</span><span>Last updated first</span></div>`}
function activityItems(limit=100){return state.activity.slice(0,limit).map(a=>`<div class="activity-item"><span class="activity-dot">${icon('check')}</span><div><p>${esc(a.text)}</p><small>${relative(a.date)}</small></div></div>`).join('')||'<p class="muted">Your workspace activity will appear here.</p>'}
function overview(){const count=s=>state.entries.filter(e=>e.status===s).length;return heading(`Let’s make good things happen<span style="color:#82a164">.</span>`,'A fresh perspective on your content. Everything you need, right here.',action('download','Export backup','secondary','export-button')+action('plus','Create content','primary','create-button'))+`<section class="welcome"><div><span class="eyebrow">A SPACE FOR YOUR IDEAS</span><h2>Great content starts here.</h2><p>From the first spark to the final publish.<br>Your next story is waiting to be told.</p><button class="text-link" data-create="Article">Create your next story ${icon('arrow')}</button></div><div class="welcome-art" aria-hidden="true"><div class="orbit"></div><div class="orbit two"></div><span class="sparkle">✧</span><div class="art-card back"></div><div class="art-card"><div class="art-picture"></div><div class="art-line"></div><div class="art-line short"></div><div class="art-line short"></div></div><span class="art-badge">${icon('check')}</span></div></section><div class="stats">${[['Total content',state.entries.length,'content','Your ideas, all in one place'],['Published',count('Published'),'check','Ready for your audience'],['In progress',count('Draft')+count('In review'),'edit','Good things in the making'],['Scheduled',count('Scheduled'),'calendar','Coming up next']].map(([label,value,i,sub])=>`<div class="stat"><div class="stat-label">${label}<span class="stat-icon">${icon(i)}</span></div><div class="stat-value">${value.toString().padStart(2,'0')}</div><div class="stat-bottom"><span>↗</span>${sub}</div></div>`).join('')}</div><div class="lower-grid">${contentPanel()}<div class="right-stack"><section class="panel"><div class="panel-head"><h2>Make your next move</h2><span style="color:#a7b09b">↗</span></div><div class="quick-list">${[['content','Write an article','Turn an idea into a story','data-create="Article"'],['upload','Upload media','Give your content some life','data-upload'],['overview','Create a page','Make room for something new','data-create="Page"']].map(([i,t,s,a])=>`<button class="quick-action" ${a}><span class="quick-icon">${icon(i)}</span><span><strong>${t}</strong><small>${s}</small></span><span>↗</span></button>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>Recent activity</h2><button class="text-link" data-nav="activity">View all ↗</button></div><div class="activity-list">${activityItems(3)}</div></section><div class="tip"><strong>${icon('bulb')} A little studio tip</strong><p>Good ideas don’t keep office hours. Save a draft now, make it great later.</p></div></div></div>`}
function mediaPage(){return heading('Your visual library.','A home for the images that bring your stories to life.',action('upload','Upload media','primary','upload-button'))+(state.media.length?`<div class="media-grid">${state.media.map(m=>`<div class="media-card"><img src="${esc(m.data)}" alt="${esc(m.name)}"><div class="media-info"><div><strong>${esc(m.name)}</strong><small>${Math.round(m.size/1024)} KB · ${dateLabel(m.date)}</small></div><button class="icon-button danger" data-remove-media="${m.id}" aria-label="Delete ${esc(m.name)}">${icon('trash')}</button></div></div>`).join('')}</div>`:'<div class="panel empty"><h3>A blank canvas for your visuals.</h3><p>Upload images to start your media library.<br>PNG, JPEG, GIF, WebP, or AVIF · up to 1 MB per image</p><button class="button primary" data-upload>Upload your first image ↗</button></div>')}
function calendarPage(){const entries=state.entries.filter(e=>['Scheduled','Published'].includes(e.status)).sort((a,b)=>new Date(a.date)-new Date(b.date));return heading('Every story has its moment.','Your publishing schedule, with everything in view.',action('plus','Schedule content','primary','schedule-button'))+`<section class="panel"><div class="panel-head"><div><h2>Publishing timeline</h2><p>Scheduled and published content · ordered by publish date</p></div></div><div class="calendar-list">${entries.map(e=>`<div class="schedule-item"><div class="date-block"><small>${new Date(e.date).toLocaleDateString('en-GB',{month:'short'}).toUpperCase()}</small><strong>${new Date(e.date).getDate()}</strong></div><div><h3>${esc(e.title)}</h3>${badge(e.status)} <span class="muted">${new Date(e.date).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div><button class="button secondary" data-edit="${e.id}">Edit ↗</button></div>`).join('')||'<div class="empty">No publishing dates yet. Schedule your first story.</div>'}</div></section>`}
function settingsPage(){return heading('Make yourself at home.','The details that make this workspace yours.')+`<form class="panel settings-panel" id="settings-form"><h2>Workspace details</h2><div class="setting-row"><div><label for="settings-name">Your display name</label><input id="settings-name" value="${esc(state.settings.name)}" maxlength="80" required></div><div><label for="settings-workspace">Workspace name</label><input id="settings-workspace" value="${esc(state.settings.workspace)}" maxlength="80" required></div></div><button class="button primary">Save changes</button></form><section class="panel settings-panel"><h2>Your data, in your hands.</h2><p class="muted">Content and media are saved in your server database. Export a backup to keep an offline copy. Importing a backup replaces the current content, media, and workspace details; your login stays the same.</p><div class="heading-actions">${action('download','Export backup','secondary','export-button')}${action('upload','Import backup','secondary','import-button')}<button type="button" class="button secondary" id="migrate-button">Import browser workspace</button></div></section><section class="panel settings-panel"><h2>Connected workspace</h2><p class="muted">Studio is connected to your server database. Published content is available on your public stories page. Scheduled publishing continues while the server is running, even with your browser closed.</p><a class="button secondary" href="/site" target="_blank" rel="noopener">View published stories ↗</a></section><form class="panel settings-panel" id="password-form"><h2>Change password</h2><p class="muted">Changing your password signs out your other sessions.</p><label for="current-password">Current password</label><input id="current-password" type="password" autocomplete="current-password" required maxlength="256"><label for="new-password">New password</label><input id="new-password" type="password" autocomplete="new-password" required minlength="12" maxlength="256"><button class="button primary">Update password</button></form>`}
function render(){shell();$('#main').innerHTML=page==='overview'?overview():page==='content'?heading('A home for every story.','Create, organize, and publish with a little more clarity.',action('plus','Create content','primary','create-button'))+contentPanel(true):page==='media'?mediaPage():page==='calendar'?calendarPage():page==='activity'?heading('Your workspace, in motion.','A history of the things you’ve made happen.')+`<section class="panel activity-full">${activityItems()}</section>`:settingsPage()}
function navigate(p){if(!signedIn)return;page=['overview','content','media','calendar','activity','settings'].includes(p)?p:'overview';filter='All content';query='';if(location.hash!==`#${page}`)location.hash=page;render()}
function localDate(d){const date=new Date(d);return new Date(date-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function openEditor(id,type='Article',scheduled=false){const e=state.entries.find(e=>e.id===id);$('#editor-error').hidden=true;$('#editor-form').reset();$('#entry-id').value=e?.id||'';$('#editor-heading').textContent=e?'A little polish. A big difference.':'Create something great.';for(const k of ['title','excerpt','body'])$(`#entry-${k}`).value=e?.[k]||'';$('#entry-type').value=e?.type||type;$('#entry-category').value=e?.category||'Design';$('#entry-status').value=e?.status||(scheduled?'Scheduled':'Draft');$('#entry-date').value=localDate(e?.date||Date.now()+86400000);$('#editor-dialog').showModal();$('#entry-title').focus()}
$('#editor-form').addEventListener('submit',async event=>{event.preventDefault();const id=$('#entry-id').value;const status=$('#entry-status').value;const rawDate=$('#entry-date').value;const date=new Date(rawDate);if(!$('#entry-title').value.trim()){toast('Please add a title.');return}if(Number.isNaN(date.getTime())){toast('Please select a valid publish date.');return}if(status==='Scheduled'&&date<=new Date()){toast('Choose a future date for scheduled content.');return}const entry={id:id||crypto.randomUUID(),title:$('#entry-title').value.trim(),excerpt:$('#entry-excerpt').value.trim(),body:$('#entry-body').value,type:$('#entry-type').value,status,category:$('#entry-category').value,date:date.toISOString(),updated:new Date().toISOString()};if(await commit(()=>{const idx=state.entries.findIndex(e=>e.id===id);if(idx>=0)state.entries[idx]=entry;else state.entries.unshift(entry);})){$('#editor-dialog').close();render();toast('Content saved.')}});
function preview(id){const e=state.entries.find(e=>e.id===id);if(!e)return;$('#preview').innerHTML=`${badge(e.status)} <span class="muted">${esc(e.category)} · ${esc(e.type)}</span><h1>${esc(e.title)}</h1><p style="font-size:18px">${esc(e.excerpt)}</p><hr style="border:0;border-top:1px solid #e6e9e4"><p>${esc(e.body)}</p>`;$('#preview-dialog').showModal()}
async function exportBackup(){try{const backup=await api('/api/backup');const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`studio-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Database content backup exported.');}catch(error){toast(error.message)}}
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;if(busy&&!b.classList.contains('close-dialog'))return;if(b.id==='logout-button'){await logout();return;}if(b.id==='refresh-button'||b.id==='editor-refresh'){await refreshWorkspace();return;}if(b.id==='migrate-button'){await migrateBrowser();return;}if(b.dataset.nav)navigate(b.dataset.nav);if(b.classList.contains('close-dialog'))b.closest('dialog').close();if(b.dataset.create||b.id==='create-button')openEditor(null,b.dataset.create||'Article');if(b.id==='schedule-button')openEditor(null,'Article',true);if(b.dataset.edit)openEditor(b.dataset.edit);if(b.dataset.preview)preview(b.dataset.preview);if(b.dataset.filter){filter=b.dataset.filter;render()}if(b.id==='export-button')exportBackup();if(b.id==='import-button')$('#import-input').click();if(b.hasAttribute('data-upload')||b.id==='upload-button')$('#upload-input').click();if(['profile','top-profile','workspace'].includes(b.id))navigate('settings');if(b.id==='search-button'){navigate('content');$('#content-search').focus()}if(b.dataset.delete){const e=state.entries.find(e=>e.id===b.dataset.delete);if(e&&confirm(`Delete “${e.title}”? This cannot be undone.`)&&await commit(()=>{state.entries=state.entries.filter(x=>x.id!==e.id);})){render();toast('Content deleted.')}}if(b.dataset.copy){const e=state.entries.find(e=>e.id===b.dataset.copy);if(e&&await commit(()=>{state.entries.unshift({...e,id:crypto.randomUUID(),title:`${e.title.slice(0,193)} (copy)`,status:'Draft',updated:new Date().toISOString()});})){render();toast('Draft duplicated.')}}if(b.dataset.removeMedia){const m=state.media.find(m=>m.id===b.dataset.removeMedia);if(m&&confirm(`Remove “${m.name}” from the media library?`)&&await commit(()=>{state.media=state.media.filter(x=>x.id!==m.id);})){render();toast('Media removed.')}}});
document.addEventListener('input',event=>{if(event.target.id==='content-search'){query=event.target.value;$('#content-results').innerHTML=rows(page==='content')}});
document.addEventListener('submit',async event=>{if(event.target.id!=='settings-form')return;event.preventDefault();const name=$('#settings-name').value.trim(),workspace=$('#settings-workspace').value.trim();if(!name||!workspace){toast('Please fill in both workspace details.');return}if(await commit(()=>{state.settings={name,workspace};})){render();toast('Workspace updated.')}});
$('#upload-input').addEventListener('change',async event=>{const files=[...event.target.files];let count=0;for(const file of files){if(!['image/png','image/jpeg','image/gif','image/webp','image/avif'].includes(file.type)||file.size>1048576){toast('Use PNG, JPEG, GIF, WebP, or AVIF images under 1 MB.');continue}try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});if(await commit(()=>{state.media.unshift({id:crypto.randomUUID(),name:file.name,size:file.size,data,date:new Date().toISOString()});}))count++;else break}catch{toast(`Could not read ${file.name}.`)}}event.target.value='';if(count){navigate('media');toast(`${count} image${count===1?'':'s'} uploaded.`)}});
async function importWorkspace(imported){
  if(busy)return;
  if(!confirm('Replace server content, media, and workspace details with this backup? Your sign-in account will stay the same.'))return;
  setBusy(true);
  try{state=await api('/api/backup',{method:'PUT',body:JSON.stringify({...imported,revision:state.revision})});navigate('overview');toast('Workspace restored to the database.');}
  catch(error){toast(error.message);}
  finally{setBusy(false);}
}
$('#import-input').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>20000000){toast('Backup is too large. The limit is 20 MB.');return;}try{const imported=JSON.parse(await file.text());await importWorkspace(imported);}catch{toast('This file is not a valid JSON backup.');}});
async function migrateBrowser(){try{const raw=localStorage.getItem(KEY);if(!raw){toast('No browser workspace found at this address. Export a backup from your old app and use Import backup.');return;}await importWorkspace(JSON.parse(raw));}catch{toast('Could not read the old browser workspace. Use a JSON backup instead.');}}
async function refreshWorkspace(silent=false){
  if(!signedIn||busy)return;
  try{const latest=await api('/api/workspace');if(busy)return;if(silent&&($('#editor-dialog').open||$('#preview-dialog').open||page==='settings'||document.activeElement?.id==='content-search'))return;
    if(latest.revision>=state.revision&&(latest.revision!==state.revision||!silent)){state=latest;render();}if(!silent)toast('Workspace refreshed. Unsaved editor text has been kept.');
  }catch(error){if(!silent)toast(error.message);if(error.status===401)showAuth(false);}
}
function showAuth(setup){document.querySelectorAll('dialog[open]').forEach(d=>d.close());signedIn=false;csrf='';setupRequired=setup;document.body.classList.add('auth-pending');$('#auth-screen').hidden=false;$('#auth-title').textContent=setup?'Your studio starts here.':'Welcome back to your studio.';$('#auth-description').textContent=setup?'Create the owner account to start your connected workspace.':'Sign in to manage your content and publishing.';$('#auth-name-field').hidden=!setup;$('#auth-name').required=setup;$('#auth-password').minLength=setup?12:1;$('#auth-password').autocomplete=setup?'new-password':'current-password';$('#auth-submit').textContent=setup?'Create workspace':'Sign in';$('#auth-submit').disabled=false;$('#auth-email').focus();}
async function bootstrap(){
  if(location.hostname.endsWith('.github.io')){$('#auth-screen').hidden=false;$('#auth-form').hidden=true;$('#connection-help').hidden=false;$('#auth-title').textContent='Open your connected workspace.';$('#auth-description').textContent='This is the static project page. Use your Codespaces preview to sign in.';return;}
  try{const auth=await api('/api/auth/status');if(!auth.authenticated){showAuth(auth.setupRequired);return;}csrf=auth.csrf;state=await api('/api/workspace');signedIn=true;$('#auth-screen').hidden=true;document.body.classList.remove('auth-pending');navigate(location.hash.slice(1)||'overview');}
  catch(error){$('#auth-screen').hidden=false;$('#auth-title').textContent='Backend connection unavailable.';$('#auth-description').textContent='Keep npm run preview running in your Codespaces terminal, then open port 3000 from the Ports tab.';$('#auth-error').textContent=error.message;$('#auth-submit').disabled=true;$('#auth-retry').hidden=false;}
}
$('#auth-form').addEventListener('submit',async event=>{event.preventDefault();$('#auth-error').textContent='';$('#auth-submit').disabled=true;try{const auth=await api(setupRequired?'/api/auth/setup':'/api/auth/login',{method:'POST',body:JSON.stringify({name:$('#auth-name').value.trim(),email:$('#auth-email').value.trim(),password:$('#auth-password').value})});csrf=auth.csrf;$('#auth-password').value='';await bootstrap();}catch(error){$('#auth-error').textContent=error.message;}finally{$('#auth-submit').disabled=false;}});
$('#auth-retry').addEventListener('click',()=>{location.reload();});
async function logout(){try{await api('/api/auth/logout',{method:'POST',body:'{}'});document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('#editor-form').reset();$('#main').innerHTML='';state={version:1,revision:0,settings:{name:'',workspace:''},entries:[],media:[],activity:[]};csrf='';showAuth(false);}catch(error){toast(error.message)}}
document.addEventListener('submit',async event=>{if(event.target.id!=='password-form')return;event.preventDefault();if(busy)return;setBusy(true);try{const result=await api('/api/auth/password',{method:'POST',body:JSON.stringify({currentPassword:$('#current-password').value,password:$('#new-password').value})});csrf=result.csrf;event.target.reset();toast('Password changed. Other sessions have been signed out.');}catch(error){toast(error.message);}finally{setBusy(false);}});
window.addEventListener('hashchange',()=>{if(location.hash.slice(1)!==page)navigate(location.hash.slice(1));});
try{$('#legacy-backup').hidden=!localStorage.getItem(KEY);}catch{}
$('#legacy-export').addEventListener('click',()=>{try{const raw=localStorage.getItem(KEY);if(!raw){toast('No browser workspace found at this address.');return;}const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='studio-browser-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Browser backup downloaded. Import it in your connected workspace.');}catch{toast('Could not export browser data.');}});
bootstrap();setInterval(()=>refreshWorkspace(true),15000);
