import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtemp, rm, access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApplication } from '../server/index.js';

const dir=await mkdtemp(join(tmpdir(),'studio-browser-'));
const origin='http://localhost:3198';
const app=createApplication({dbPath:join(dir,'browser.sqlite'),origin});
await new Promise(resolve=>app.server.listen(3198,'127.0.0.1',resolve));
let browser;
try{
  let executablePath=process.env.CHROME_PATH;
  if(!executablePath&&process.platform==='darwin'){const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';try{await access(chrome);executablePath=chrome;}catch{}}
  browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  page.on('dialog',dialog=>dialog.accept());
  await page.goto(origin);
  await page.locator('#auth-name').fill('Taylor Studio');
  await page.locator('#auth-email').fill('taylor@example.com');
  await page.locator('#auth-password').fill('browser-password-123');
  await page.locator('#auth-submit').click();
  await page.locator('#create-button').waitFor();
  await page.locator('#create-button').click();
  await page.locator('#entry-title').fill('Backend connected story');
  await page.locator('#entry-excerpt').fill('A story saved in SQLite.');
  await page.locator('#entry-body').fill('This remains after a reload.\n\nA second paragraph.');
  await page.getByRole('button',{name:'Save content'}).click();
  await page.locator('#editor-dialog').waitFor({state:'hidden'});
  await page.reload();
  await page.getByRole('button',{name:'Backend connected story',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>localStorage.getItem('studio-cms-v1')),null);
  assert.equal(app.store.read().entries.length,1);
  await page.getByRole('button',{name:'Backend connected story',exact:true}).click();
  await page.locator('#entry-status').selectOption('Published');
  await page.getByRole('button',{name:'Save content'}).click();
  await page.locator('#editor-dialog').waitFor({state:'hidden'});
  const publicPage=await browser.newPage();
  await publicPage.goto(`${origin}/site/${app.store.read().entries[0].id}`);
  assert.match(await publicPage.locator('article').innerText(),/A second paragraph/);
  assert.equal((await publicPage.request.get(`${origin}/api/workspace`)).status(),401);
  await publicPage.close();
  await page.getByRole('button',{name:'Duplicate Backend connected story',exact:true}).click();
  await page.getByRole('button',{name:'Backend connected story (copy)',exact:true}).waitFor();
  await page.getByRole('button',{name:'Delete Backend connected story (copy)',exact:true}).click();
  await page.getByRole('button',{name:'Backend connected story (copy)',exact:true}).waitFor({state:'hidden'});
  await page.locator('#upload-input').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1sAAAAASUVORK5CYII=','base64')});
  await page.locator('.media-card img').waitFor();
  await page.reload();await page.locator('.media-card img').waitFor();
  assert.equal(app.store.read().media.length,1);
  await page.locator('nav [data-nav="content"]').click();
  await page.getByRole('button',{name:'Backend connected story',exact:true}).click();
  await page.locator('#entry-title').fill('Unsaved edit kept');
  // A second writer changes the revision while the editor is open.
  const before=app.store.read();app.store.save({...before,settings:{...before.settings,workspace:'Concurrent workspace'}},before.revision);
  await page.getByRole('button',{name:'Save content'}).click();
  await page.locator('#editor-error').waitFor();
  assert.match(await page.locator('#editor-error').innerText(),/another session/);
  assert.equal(await page.locator('#entry-title').inputValue(),'Unsaved edit kept');
  await page.locator('#editor-refresh').click();
  await page.waitForFunction(()=>document.querySelector('.workspace strong').textContent==='Concurrent workspace');
  await page.getByRole('button',{name:'Save content'}).click();
  await page.locator('#editor-dialog').waitFor({state:'hidden'});
  assert.equal(app.store.read().entries[0].title,'Unsaved edit kept');
  await page.getByRole('button',{name:'Unsaved edit kept',exact:true}).click();
  await page.locator('#entry-body').fill('Preserved during connection failure.');
  await page.route('**/api/workspace',route=>route.request().method()==='PUT'?route.abort():route.continue());
  await page.getByRole('button',{name:'Save content'}).click();
  await page.locator('#editor-error').waitFor();
  assert.match(await page.locator('#editor-error').innerText(),/Cannot reach the server/);
  assert.equal(await page.locator('#entry-body').inputValue(),'Preserved during connection failure.');
  await page.unroute('**/api/workspace');
  await page.getByRole('button',{name:'Save content'}).click();
  await page.locator('#editor-dialog').waitFor({state:'hidden'});
  await page.locator('nav [data-nav="settings"]').click();
  await page.locator('#settings-name').fill('Updated Owner');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.profile strong').textContent==='Updated Owner');
  const waitDownload=page.waitForEvent('download');await page.locator('#export-button').click();
  const download=await waitDownload;await download.saveAs(join(dir,'backup.json'));
  await page.locator('#import-input').setInputFiles(join(dir,'backup.json'));
  await page.locator('#create-button').waitFor();
  await page.setViewportSize({width:390,height:844});
  for(const section of ['overview','content','media','calendar','activity','settings']){
    await page.locator(`nav [data-nav="${section}"]`).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${section} fits mobile viewport`);
  }
  await page.locator('#current-password').fill('browser-password-123');
  await page.locator('#new-password').fill('changed-browser-password-456');
  await page.getByRole('button',{name:'Update password',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#new-password').value==='');
  await page.locator('#logout-button').click();await page.locator('#auth-submit').waitFor();
  await page.locator('#auth-email').fill('taylor@example.com');
  await page.locator('#auth-password').fill('changed-browser-password-456');
  await page.locator('#auth-submit').click();await page.locator('nav').waitFor();
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('Browser checks passed: owner setup, authentication, durable CRUD, public stories, uploads, conflict recovery, offline recovery, backup round-trip, all mobile screens, password change, and sign-out/sign-in.');
}finally{await browser?.close();await new Promise(resolve=>app.server.close(resolve));await rm(dir,{recursive:true,force:true});}
